// test/lib/rules-merge.test.js
import { mergeRulesContent, isBobbyGenerated, MARKER_START, MARKER_END } from '../../lib/rules-merge.js';

describe('isBobbyGenerated', () => {
  test('returns false for null/empty content', () => {
    expect(isBobbyGenerated(null)).toBe(false);
    expect(isBobbyGenerated('')).toBe(false);
  });

  test('returns true for file with only bobby markers', () => {
    const content = `${MARKER_START}\n# Project — Bobby Workflow\nSome bobby content\n${MARKER_END}\n`;
    expect(isBobbyGenerated(content)).toBe(true);
  });

  test('returns true for file with markers and only whitespace outside', () => {
    const content = `\n\n${MARKER_START}\nBobby content\n${MARKER_END}\n\n`;
    expect(isBobbyGenerated(content)).toBe(true);
  });

  test('returns false for file with user content outside markers', () => {
    const content = `# My Project\nCustom docs here\n\n${MARKER_START}\nBobby content\n${MARKER_END}\n`;
    expect(isBobbyGenerated(content)).toBe(false);
  });

  test('returns true for legacy file with "Generated by Bobby"', () => {
    const content = '# Project\n> This file was generated by `bobby init`. Generated by Bobby.\n';
    expect(isBobbyGenerated(content)).toBe(true);
  });

  test('returns true for legacy file with "bobbycode init"', () => {
    const content = '# Project\n> Run bobbycode init to regenerate.\n';
    expect(isBobbyGenerated(content)).toBe(true);
  });

  test('returns false for pure user file', () => {
    const content = '# My Project\n\nThis is my custom CLAUDE.md with project docs.\n';
    expect(isBobbyGenerated(content)).toBe(false);
  });
});

describe('mergeRulesContent', () => {
  const bobbyContent = `${MARKER_START}\n# New Bobby Content\n${MARKER_END}`;

  test('returns bobby content when existing is null', () => {
    expect(mergeRulesContent(null, bobbyContent)).toBe(bobbyContent);
  });

  test('returns bobby content when existing is empty string', () => {
    expect(mergeRulesContent('', bobbyContent)).toBe(bobbyContent);
  });

  test('replaces content between markers when markers exist', () => {
    const existing = `# My Docs\n\n${MARKER_START}\n# Old Bobby\n${MARKER_END}\n\n## My Footer`;
    const result = mergeRulesContent(existing, bobbyContent);
    expect(result).toContain('# My Docs');
    expect(result).toContain('# New Bobby Content');
    expect(result).toContain('## My Footer');
    expect(result).not.toContain('# Old Bobby');
  });

  test('preserves user content before markers', () => {
    const existing = `# Project Overview\nArchitecture notes\n\n${MARKER_START}\nold\n${MARKER_END}`;
    const result = mergeRulesContent(existing, bobbyContent);
    expect(result).toMatch(/^# Project Overview\nArchitecture notes\n\n/);
    expect(result).toContain(MARKER_START);
  });

  test('preserves user content after markers', () => {
    const existing = `${MARKER_START}\nold\n${MARKER_END}\n\n## Custom Rules\nDo not touch prod.`;
    const result = mergeRulesContent(existing, bobbyContent);
    expect(result).toContain('## Custom Rules');
    expect(result).toContain('Do not touch prod.');
  });

  test('appends when no markers exist', () => {
    const existing = '# My Project\nCustom documentation.';
    const result = mergeRulesContent(existing, bobbyContent);
    expect(result).toMatch(/^# My Project\nCustom documentation\.\n\n/);
    expect(result).toContain(bobbyContent);
  });

  test('handles markers at very start and end of file', () => {
    const existing = `${MARKER_START}\nold content\n${MARKER_END}`;
    const result = mergeRulesContent(existing, bobbyContent);
    expect(result).toBe(bobbyContent);
  });
});
