// lib/config.js
import fs from 'fs';
import path from 'path';
import { execSync } from 'child_process';
import YAML from 'yaml';

const CONFIG_FILE = '.bobbyrc.yml';

const DEFAULTS = {
  bobby_dir: '.bobby',
  ticket_prefix: 'TKT',
  idea_prefix: 'IDEA',
  target: 'claude-code',
  health_checks: [],
  areas: [],
  skill_routing: {},
  backlog_limit: null,
  backlog_stale_days: 30,
  parallel_isolation: 'none',
  testing_tools: ['curl'],
  dashboard: {
    port: 7777,
    worktree_root: '../bobby-wt',
    auto_approve_stages: [],
    auto_merge: false,
    sandbox: 'worktree',
    executor: 'claude',
  },
};

export function readConfig(rootDir) {
  const configPath = path.join(rootDir, CONFIG_FILE);
  if (!fs.existsSync(configPath)) {
    throw new Error('Not a Bobby project. Run `bobby init` first.');
  }
  const raw = fs.readFileSync(configPath, 'utf8');
  const parsed = YAML.parse(raw) || {};
  const merged = { ...DEFAULTS, ...parsed };

  // Derive tickets_dir and sessions_dir from bobby_dir unless explicitly set
  const bobbyDir = merged.bobby_dir;
  if (!parsed.tickets_dir) merged.tickets_dir = `${bobbyDir}/tickets`;
  if (!parsed.sessions_dir) merged.sessions_dir = `${bobbyDir}/sessions`;

  return merged;
}

export function writeConfig(rootDir, config) {
  const configPath = path.join(rootDir, CONFIG_FILE);
  const content = YAML.stringify(config, { lineWidth: 120 });
  fs.writeFileSync(configPath, content, 'utf8');
}

export function writeConfigCommented(rootDir, config) {
  const configPath = path.join(rootDir, CONFIG_FILE);
  const lines = [];

  lines.push('# Bobby Configuration');
  lines.push('# Generated by: npx bobbycode init');
  lines.push('# Docs: https://github.com/ccevans/bobbycode');
  lines.push('');

  // Project name
  lines.push('# Project name (used in ticket board headers and PR titles)');
  lines.push(`project: ${config.project}`);
  lines.push('');

  // Stack
  lines.push('# Tech stack preset. Determines default commands, areas, and health checks.');
  lines.push('# Options: nextjs | rails-react | python-flask | polyglot | generic');
  lines.push(`stack: ${config.stack}`);
  lines.push('');

  // Target
  lines.push('# AI target. Determines where skills/agents/commands are scaffolded.');
  lines.push('# Options: claude-code | cline');
  lines.push(`target: ${config.target || 'claude-code'}`);
  lines.push('');

  // Directories
  lines.push('# Directory where Bobby stores tickets, sessions, and metadata.');
  lines.push(`bobby_dir: ${config.bobby_dir || '.bobby'}`);
  lines.push(`tickets_dir: ${config.tickets_dir}`);
  lines.push(`sessions_dir: ${config.sessions_dir}`);
  lines.push('');

  // Ticket prefix
  lines.push('# Prefix for ticket IDs (e.g., TKT-001, PROJ-001)');
  lines.push(`ticket_prefix: ${config.ticket_prefix || 'TKT'}`);
  lines.push('');

  // Health checks
  lines.push('# Health check URLs verified before agents start work.');
  lines.push('# Add your dev server URL(s) so agents can confirm the app is running.');
  if (config.health_checks && config.health_checks.length > 0) {
    lines.push('health_checks:');
    for (const hc of config.health_checks) {
      lines.push(`  - name: ${hc.name}`);
      lines.push(`    url: ${hc.url}`);
      if (hc.description) lines.push(`    description: ${hc.description}`);
    }
  } else {
    lines.push('health_checks: []');
  }
  lines.push('');

  // Areas
  lines.push('# Feature areas for categorizing tickets. Used by `bobby create --area`.');
  if (config.areas && config.areas.length > 0) {
    lines.push('areas:');
    for (const area of config.areas) {
      lines.push(`  - ${area}`);
    }
  } else {
    lines.push('areas: []');
  }
  lines.push('');

  // Commands
  lines.push('# Shell commands Bobby uses for dev, test, lint, and build.');
  const cmds = config.commands || {};
  lines.push('commands:');
  lines.push(`  dev: ${cmds.dev || ''}`);
  lines.push(`  test: ${cmds.test || ''}`);
  lines.push(`  lint: ${cmds.lint || ''}`);
  lines.push(`  build: ${cmds.build || ''}`);
  lines.push('');

  // Testing tools
  lines.push('# Tools available for the test agent (e.g., playwright, curl)');
  const tools = config.testing_tools || ['curl'];
  lines.push('testing_tools:');
  for (const tool of tools) {
    lines.push(`  - ${tool}`);
  }
  lines.push('');

  // Max retries
  lines.push('# Max retry loops when review/test rejects code (per ticket)');
  lines.push(`max_retries: ${config.max_retries || 3}`);
  lines.push('');

  // Repos (if present)
  if (config.repos && config.repos.length > 0) {
    lines.push('# Multi-repo shipping (PR created per repo)');
    lines.push('repos:');
    for (const repo of config.repos) {
      lines.push(`  - name: ${repo.name}`);
      lines.push(`    path: ${repo.path}`);
    }
    lines.push('');
  }

  // Services (if present)
  if (config.services && Object.keys(config.services).length > 0) {
    lines.push('# Multi-service configuration (per-service commands and health checks)');
    lines.push(YAML.stringify({ services: config.services }, { lineWidth: 120 }).trim());
    lines.push('');
  }

  // Build skills (if present)
  if (config.build_skills && config.build_skills.length > 0) {
    lines.push('# Project-specific skills the build agent should follow.');
    lines.push('build_skills:');
    for (const skill of config.build_skills) {
      lines.push(`  - ${skill}`);
    }
    lines.push('');
  }

  // --- Optional sections (commented out) ---
  lines.push('# ──────────────────────────────────────────────────────────');
  lines.push('# Optional configuration — uncomment and customize as needed');
  lines.push('# ──────────────────────────────────────────────────────────');
  lines.push('');

  if (!config.pipelines) {
    lines.push('# Custom pipelines. The "default" pipeline is used by `bobby run pipeline`.');
    lines.push('# pipelines:');
    lines.push('#   default: [plan, build, review, test]');
    lines.push('#   secure: [plan, build, security, review, test]');
    lines.push('#   fast: [plan, build, test]');
    lines.push('');
  }

  if (!config.skill_routing || Object.keys(config.skill_routing).length === 0) {
    lines.push('# Skill routing: maps areas to project skill directories for targeted guidance.');
    lines.push('# skill_routing:');
    lines.push('#   auth: [dev/fullstack]');
    lines.push('#   api: [dev/backend]');
    lines.push('#   dashboard: [dev/frontend]');
    lines.push('');
  }

  if (!config.build_skills) {
    lines.push('# Project-specific skills the build agent should follow.');
    lines.push('# These are non-bobby skills in your .claude/skills/ directory.');
    lines.push('# build_skills:');
    lines.push('#   - api-patterns');
    lines.push('#   - component-library');
    lines.push('');
  }

  lines.push('# Backlog management');
  lines.push('# backlog_limit: 50          # Warn when backlog exceeds this count');
  lines.push('# backlog_stale_days: 30     # Days before a ticket is considered stale');
  lines.push('');

  if (!config.repos) {
    lines.push('# Multi-repo shipping (for monorepo or multi-repo projects)');
    lines.push('# repos:');
    lines.push('#   - name: api');
    lines.push('#     path: backend-api');
    lines.push('#   - name: ui');
    lines.push('#     path: frontend-ui');
    lines.push('');
  }

  lines.push('# Parallel isolation mode for batch operations');
  lines.push('# parallel_isolation: none   # Options: none | worktree');
  lines.push('');

  // Local dev profiles (if present)
  if (config.local && Object.keys(config.local).length > 0) {
    lines.push('# Local dev profiles. Run `/bobby-local <profile>` to start a named environment.');
    lines.push('local:');
    for (const [name, profile] of Object.entries(config.local)) {
      lines.push(`  ${name}:`);
      if (profile.subdomain) lines.push(`    subdomain: ${profile.subdomain}`);
      if (profile.compose_project) lines.push(`    compose_project: ${profile.compose_project}`);
      if (profile.description) lines.push(`    description: ${profile.description}`);
      if (profile.ports && Object.keys(profile.ports).length > 0) {
        const portParts = Object.entries(profile.ports).map(([k, v]) => `${k}: ${v}`);
        lines.push(`    ports: { ${portParts.join(', ')} }`);
      }
      if (profile.health_checks && profile.health_checks.length > 0) {
        lines.push('    health_checks:');
        for (const hc of profile.health_checks) {
          lines.push(`      - name: ${hc.name}`);
          lines.push(`        url: ${hc.url}`);
          if (hc.description) lines.push(`        description: ${hc.description}`);
        }
      }
    }
    lines.push('');
  }

  fs.writeFileSync(configPath, lines.join('\n') + '\n', 'utf8');
}

export function configExists(rootDir) {
  return fs.existsSync(path.join(rootDir, CONFIG_FILE));
}

export function findProjectRoot(startDir = process.cwd()) {
  let dir = startDir;
  while (dir !== path.dirname(dir)) {
    if (fs.existsSync(path.join(dir, CONFIG_FILE))) return dir;
    dir = path.dirname(dir);
  }
  throw new Error('Not a Bobby project. Run `bobby init` first.');
}

/**
 * If cwd is inside a git worktree, return the main worktree's root.
 * Returns null if not in a worktree or git unavailable.
 */
export function findMainWorktreeRoot() {
  try {
    const gitDir = execSync('git rev-parse --git-dir', { encoding: 'utf8', stdio: ['pipe', 'pipe', 'pipe'] }).trim();
    const gitCommonDir = execSync('git rev-parse --git-common-dir', { encoding: 'utf8', stdio: ['pipe', 'pipe', 'pipe'] }).trim();
    const absGitDir = path.resolve(gitDir);
    const absCommonDir = path.resolve(gitCommonDir);
    if (absGitDir !== absCommonDir) {
      return path.resolve(absCommonDir, '..');
    }
  } catch { /* not in git repo */ }
  return null;
}

/**
 * Resolve the tickets directory — always points to the main worktree's copy.
 */
export function resolveTicketsDir(root, config) {
  const mainRoot = findMainWorktreeRoot();
  const effectiveRoot = (mainRoot && mainRoot !== root) ? mainRoot : root;
  return path.join(effectiveRoot, config.tickets_dir);
}

/**
 * Resolve the sessions directory — always points to the main worktree's copy.
 */
export function resolveSessionsDir(root, config) {
  const mainRoot = findMainWorktreeRoot();
  const effectiveRoot = (mainRoot && mainRoot !== root) ? mainRoot : root;
  return path.join(effectiveRoot, config.sessions_dir);
}
