// lib/rules-merge.js
const MARKER_START = '<!-- bobby:start -->';
const MARKER_END = '<!-- bobby:end -->';

/**
 * Returns true if the file content is entirely Bobby-generated
 * (only Bobby marker content, or legacy "Generated by Bobby" files).
 */
export function isBobbyGenerated(content) {
  if (!content) return false;

  const startIdx = content.indexOf(MARKER_START);
  const endIdx = content.lastIndexOf(MARKER_END);

  if (startIdx !== -1 && endIdx !== -1) {
    // Has markers — check if content outside markers is only whitespace
    const before = content.slice(0, startIdx).trim();
    const after = content.slice(endIdx + MARKER_END.length).trim();
    return before === '' && after === '';
  }

  // Legacy detection (no markers)
  return content.includes('Generated by Bobby') || content.includes('bobbycode init');
}

/**
 * Merge Bobby-generated content into an existing rules file.
 * - existing has markers → replace between them (inclusive)
 * - existing has no markers → append bobby content at end
 * - existing is null/empty → return bobby content as-is
 */
export function mergeRulesContent(existing, bobbyContent) {
  if (!existing) return bobbyContent;

  const startIdx = existing.indexOf(MARKER_START);
  const endIdx = existing.lastIndexOf(MARKER_END);

  if (startIdx !== -1 && endIdx !== -1) {
    const before = existing.slice(0, startIdx);
    const after = existing.slice(endIdx + MARKER_END.length);
    return before + bobbyContent + after;
  }

  // No markers — append
  return existing.trimEnd() + '\n\n' + bobbyContent;
}

export { MARKER_START, MARKER_END };
